apiVersion: v1
kind: pod
metadata:
   name: myapp-pod
   labels:
     name: pod
     type: frontend
spec: 
   containers:
     - image: image
     name:  my-name
     env:
       - name:  ENVVARNAME
         value:  ENVVARVALUE